version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
  e2e:
    build: .
    command: npm run test:ci
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
    environment:
      DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@db:5432/$DATABASE?schema=public"
    depends_on:
      db:
        condition: service_healthy
